/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "querytele_constants.h"

namespace querytele {

const queryteleConstants g_querytele_constants;

queryteleConstants::queryteleConstants() {
}

} // namespace

