#******************************************************************************************
# $Id$
#
# Copyright (C) 2009-2012 Calpont Corporation
# All rights reserved
#*****************************************************************************************/
include ../../rules.mak
install: 
	cp -p infinidb_hadoop_bulkload.sh $(INSTALL_ROOT_BIN)

