#!/bin/bash
#
# $Id: post-install 1886 2010-04-01 18:30:38Z dhill $
#
# Post-install steps for calpont install

prefix=/usr/local
rpmmode=install

for arg in "$@"; do
	if [ `expr -- "$arg" : '--prefix='` -eq 9 ]; then
		prefix="`echo $arg | awk -F= '{print $2}'`"
	elif [ `expr -- "$arg" : '--rpmmode='` -eq 10 ]; then
		rpmmode="`echo $arg | awk -F= '{print $2}'`"
	else
		echo "ignoring unknown argument: $arg" 1>&2
	fi
done

#check 64-bit OS compatiable
arch=`uname -m`
patcnt=`expr "$arch" : 'i.86'`
is64bitos=1
if [ $patcnt -ne 0 ]; then
	is64bitos=0
fi
is64bitpkg=1
file ${prefix}/Calpont/bin/PrimProc | grep '64-bit' >/dev/null 2>&1
if [ $? -ne 0 ]; then
	is64bitpkg=0
fi
if [ $is64bitpkg -eq 1 -a $is64bitos -ne 1 ]; then
	echo "ERROR: Incompatible version, package is intended for a x86_64 architecture"
	echo "exiting...."
	exit 1
fi

if [ ! -f ${prefix}/Calpont/etc/Calpont.xml ]; then
	echo "${prefix}/Calpont/etc/Calpont.xml not found, exiting"
	exit 1
fi

cd ${prefix}/Calpont/lib || exit 1
for lib in *.so.1.0.0; do
	blib=`basename $lib .1.0.0`
	ln -sf $lib $blib
	ln -sf $lib $blib.1
done
chown -h root.root *.so
if [ -f libnetsnmp.so.5.2.1 ]; then
	for lib in *.so.5.2.1; do
		blib=`basename $lib .5.2.1`
		ln -sf $lib $blib
		ln -sf $lib ${blib}.5
	done
	chown -h root.root *.so *.so.5
fi

cd /
test -d /var/log/Calpont || mkdir /var/log/Calpont
test -d /var/log/Calpont/archive || mkdir /var/log/Calpont/archive
test -d /var/log/Calpont/corefiles || mkdir /var/log/Calpont/corefiles
test -d /var/log/Calpont/trace || mkdir /var/log/Calpont/trace
# make sure trace dir is world-writable and sticky
chmod 1777 /var/log/Calpont/trace
test -d ${prefix}/Calpont/data || mkdir ${prefix}/Calpont/data
test -d ${prefix}/Calpont/data1 || mkdir ${prefix}/Calpont/data1
test -d ${prefix}/Calpont/data1/systemFiles || mkdir ${prefix}/Calpont/data1/systemFiles
test -d ${prefix}/Calpont/data1/systemFiles/dataTransaction || mkdir ${prefix}/Calpont/data1/systemFiles/dataTransaction
test -d ${prefix}/Calpont/data1/systemFiles/dataTransaction/archive || mkdir ${prefix}/Calpont/data1/systemFiles/dataTransaction/archive
test -d ${prefix}/Calpont/data1/systemFiles/dbrm || mkdir ${prefix}/Calpont/data1/systemFiles/dbrm
chmod -R 1777 ${prefix}/Calpont/data1/systemFiles/dbrm > /dev/null 2>&1
chmod -R 1777 ${prefix}/Calpont/data1 > /dev/null 2>&1
chmod -R 1777 ${prefix}/Calpont/etc > /dev/null 2>&1
test -d /var/log/Calpont/data || ln -sf ${prefix}/Calpont/data1/systemFiles/dataTransaction /var/log/Calpont/data

#create infinidb temp file directory
mkdir -p /tmp/infinidb_tmp_files

#create the bulk-load dirs
mkdir -p ${prefix}/Calpont/data/bulk/data/import >/dev/null 2>&1
mkdir -p ${prefix}/Calpont/data/bulk/log >/dev/null 2>&1
mkdir -p ${prefix}/Calpont/data/bulk/job >/dev/null 2>&1
mkdir -p ${prefix}/Calpont/data/bulk/rollback >/dev/null 2>&1
mkdir -p ${prefix}/Calpont/data/bulk/tmpjob >/dev/null 2>&1
rm -f ${prefix}/Calpont/data/bulk/tmpjob/* >/dev/null 2>&1

#setup core file directory and link
mkdir /var/log/Calpont/corefiles > /dev/null 2>&1
chmod 777 /var/log/Calpont/corefiles 

#create mount directories
mkdir /mnt/tmp > /dev/null 2>&1
mkdir /var/log/Calpont/data/archive > /dev/null 2>&1

# install Calpont Log Rotate File
cp ${prefix}/Calpont/bin/calpontLogRotate /etc/logrotate.d/calpont > /dev/null 2>&1
cp ${prefix}/Calpont/bin/transactionLog /etc/cron.d/.
chmod 644 /etc/cron.d/transactionLog

#log install message
test -f /usr/local/Calpont/post/functions && . /usr/local/Calpont/post/functions
cplogger -i 100 "***** InfiniDB Installed *****"

exit 0

