#! /bin/sh
#
# $Id: post-mysql-install 1995 2010-07-02 13:59:21Z rdempsey $
#
# Post-install steps for calpont-mysql install

prefix=/usr/local
rpmmode=install
password=" "
for arg in "$@"; do
	if [ `expr -- "$arg" : '--prefix='` -eq 9 ]; then
		prefix="`echo $arg | awk -F= '{print $2}'`"
	elif [ `expr -- "$arg" : '--rpmmode='` -eq 10 ]; then
		rpmmode="`echo $arg | awk -F= '{print $2}'`"
	elif [ `expr -- "$arg" : '--password='` -eq 11 ]; then
		password="`echo $arg | awk -F= '{print $2}'`"
	else
		echo "ignoring unknown argument: $arg" 1>&2
	fi
done

if [ -f ${prefix}/Calpont/lib/libcalmysql.so.1.0.0 ]; then
	libcalmysql=${prefix}/Calpont/lib/libcalmysql.so.1.0.0
elif [ -f ${prefix}/Calpont/lib/libcalmysql.so.1 ]; then
	libcalmysql=${prefix}/Calpont/lib/libcalmysql.so.1
else
	libcalmysql=
fi

if [ -d ${prefix}/Calpont/mysql/lib/mysql/plugin -a -n "$libcalmysql" ]; then
	cd ${prefix}/Calpont/mysql/lib/mysql/plugin
	ln -sf $libcalmysql libcalmysql.so
fi
/sbin/ldconfig
if [ -x /etc/init.d/mysql-Calpont ]; then

	# Restart in the same way that mysqld will be started normally.
	/etc/init.d/mysql-Calpont start

	sleep 2

	# Install various Calpont stuff...
	${prefix}/Calpont/mysql/install_calpont_mysql.sh --password=$password

	/etc/init.d/mysql-Calpont stop
fi

/sbin/ldconfig
exit 0
