#!/bin/bash
#
# $Id: post-mysqld-install 1995 2010-07-02 13:59:21Z rdempsey $
#
# $Id: post-mysqld-install 3663 2013-06-25 22:04:58Z dhill $
#
# Post-install steps for calpont-mysqld install

prefix=/usr/local
rpmmode=install
for arg in "$@"; do
	if [ `expr -- "$arg" : '--prefix='` -eq 9 ]; then
		prefix="`echo $arg | awk -F= '{print $2}'`"
	elif [ `expr -- "$arg" : '--rpmmode='` -eq 10 ]; then
		rpmmode="`echo $arg | awk -F= '{print $2}'`"
	else
		echo "ignoring unknown argument: $arg" 1>&2
	fi
done

cd ${prefix}/Calpont/mysql/lib/mysql
for file in libmysqlclient libmysqlclient_r; do
	ln -sf $file.so.16.0.0 $file.so
	ln -sf $file.so.16.0.0 $file.so.16
done
cd ${prefix}/Calpont/mysql/lib/mysql/plugin
for file in ha_archive ha_blackhole ha_federated ha_innodb ha_innodb_plugin; do
	ln -sf $file.so.0.0.0 $file.so
	ln -sf $file.so.0.0.0 $file.so.0
done

### taken from MySQL-server-5.1.30-0.glibc23.i386.rpm
mysql_datadir=${prefix}/Calpont/mysql/db

# Create data directory if needed
if test ! -d $mysql_datadir; then mkdir -m 755 $mysql_datadir; fi
if test ! -d $mysql_datadir/mysql; then mkdir $mysql_datadir/mysql; fi
if test ! -d $mysql_datadir/test; then mkdir $mysql_datadir/test; fi

# Create a MySQL user and group. Do not report any problems if it already
# exists.
groupadd -r mysql 2> /dev/null || true
useradd -m -r -d $mysql_datadir -s /bin/bash -c "MySQL server" -g mysql mysql 2> /dev/null || true
# The user may already exist, make sure it has the proper group nevertheless (BUG#12823)
usermod -g mysql mysql 2> /dev/null || true

# Change permissions so that the user that will run the MySQL daemon
# owns all database files.
chown -R mysql:mysql $mysql_datadir

# Initiate databases if needed
### Don't give the user the notes, we'll fix them ourselves...
${prefix}/Calpont/mysql/bin/mysql_install_db --rpm --user=mysql --defaults-file=${prefix}/Calpont/mysql/my.cnf --basedir=${prefix}/Calpont/mysql >/dev/null
# Change permissions again to fix any new files.
chown -R mysql:mysql $mysql_datadir

# Fix permissions for the permission database so that only the user
# can read them.
chmod -R og-rw $mysql_datadir/mysql

# Change permissions again to fix any new files.
chown -R mysql.mysql ${prefix}/Calpont/mysql

test -e /etc/init.d/mysql-Calpont || cp ${prefix}/Calpont/mysql/mysql-Calpont /etc/init.d

# Make MySQL start/shutdown automatically when the machine does it.
if [ -x /sbin/chkconfig ]; then
	/sbin/chkconfig --add mysql-Calpont > /dev/null 2>&1
	/sbin/chkconfig mysql-Calpont on > /dev/null 2>&1
elif [ -x /usr/sbin/update-rc.d ]; then
	/usr/sbin/update-rc.d mysql-Calpont defaults > /dev/null 2>&1
fi

if [ -f ${prefix}/Calpont/lib/libcalmysql.so.1.0.0 ]; then
	libcalmysql=${prefix}/Calpont/lib/libcalmysql.so.1.0.0
elif [ -f ${prefix}/Calpont/lib/libcalmysql.so.1 ]; then
	libcalmysql=${prefix}/Calpont/lib/libcalmysql.so.1
else
	libcalmysql=
fi

if [ -n "$libcalmysql" ]; then

	cd ${prefix}/Calpont/mysql/lib/mysql/plugin
	ln -sf $libcalmysql libcalmysql.so
fi

exit 0
