#! /bin/sh
#
# $Id: post-uninstall 421 2007-04-05 15:46:55Z dhill $
#
# Post-uninstall steps for calpont install

prefix=/usr/local

#stop services
/etc/init.d/infinidb stop > /dev/null 2>&1
if test -f /etc/init.d/calpont-Mysql ; then
	/etc/init.d/calpont-Mysql stop > /dev/null 2>&1
fi

# uninstall OS scripts updated by postConfigure
DBRootStorageType=`/usr/local/Calpont/bin/getConfig -c /usr/local/Calpont/etc/Calpont.xml Installation DBRootStorageType`
if [ "$DBRootStorageType" = "storage" ]; then
	sed -i '/^[^#].*\/usr\/local\/Calpont\/data[^ ]/d' /etc/fstab
fi
if test -f /root/.bashrc.calpontSave ; then
	mv -f /root/.bashrc.calpontSave /root/.bashrc > /dev/null 2>&1
fi
if test -f /etc/rc.local.calpontSave ; then
	mv -f /etc/rc.local.calpontSave /etc/rc.local > /dev/null 2>&1
fi

#umount file systems
rm -f ${prefix}/Calpont/data*/OAMdbrootCheck > /dev/null 2>&1
umount -fl ${prefix}/Calpont/data*  > /dev/null 2>&1
rm -f ${prefix}/Calpont/data*/OAMdbrootCheck > /dev/null 2>&1

#remove log file directories
#rm -rf /var/log/Calpont > /dev/null 2>&1
#rm -f ${prefix}/Calpont/mysql/db/*.err > /dev/null 2>&1
rm -f /var/log/Calpont/activeAlarms > /dev/null 2>&1
rm -f /var/log/Calpont/*.log1 > /dev/null 2>&1

# remove Calpont Log Rotate File abd Transaction Log File
rm -f /etc/logrotate.d/calpont > /dev/null 2>&1
rm -f /etc/cron.d/transactionLog > /dev/null 2>&1

# delete Calpont shared memory segments
${prefix}/Calpont/bin/clearShm  > /dev/null 2>&1

# delete prat files
rm -f /etc/pscollect
if [ -f /etc/cron.d/ps ]; then
	rm -f /etc/cron.d/ps
	/etc/init.d/crond reload  > /dev/null 2>&1
fi

# delete tmp files
rm -f ${prefix}/Calpont/local/*.calpont
rm -rf ${prefix}/Calpont/local/etc/
rm -rf /tmp/bucketreuse
rm -f /tmp/calpont.txt
rm -f /tmp/dbbuilder.*
rm -f /tmp/dbrmfiles
rm -f /var/lock/subsys/infinidb
rm -f /tmp/pkgcheck
rm -f /tmp/upgrade-status.log.*
rm -f /tmp/mount.log
rm -f /tmp/idb*
rm -f ${prefix}/Calpont/data/bulk/tmpjob/* >/dev/null 2>&1
rm -rf /tmp/infinidb_tmp_files

# delete core files
rm -f /var/log/Calpont/corefiles/*

#un-setup InfiniDB system logging
if [ -x ${prefix}/Calpont/bin/syslogSetup.sh ]; then
	${prefix}/Calpont/bin/syslogSetup.sh uninstall >/dev/null 2>&1
fi

if [ -x /sbin/chkconfig ]; then
	/sbin/chkconfig infinidb off > /dev/null 2>&1
	/sbin/chkconfig --del infinidb > /dev/null 2>&1
elif [ -x /usr/sbin/update-rc.d ]; then
	/usr/sbin/update-rc.d -f infinidb remove > /dev/null 2>&1
fi
rm -f /etc/init.d/infinidb

#make copy of Calpont.xml for non rpm installs
if [ -z "$1" ]; then
	/bin/cp -f ${prefix}/Calpont/etc/Calpont.xml ${prefix}/Calpont/etc/Calpont.xml.rpmsave > /dev/null 2>&1
	/bin/cp -f ${prefix}/Calpont/mysql/my.cnf ${prefix}/Calpont/mysql/my.cnf.rpmsave > /dev/null 2>&1
fi

#tell user to run post configure script
echo " "
echo "Calpont uninstall completed"

exit 0

